pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'testdeploy',
                    credentialsId: 'ce02cb56-bbec-4734-9d12-44b8ecda24af',
                    url: 'https://github.com/Capstone-Project-Warehouse-68/Capstone-Warehouse.git'
            }
        }

        stage('Build Backend') {
            steps {
                sh 'docker build -t jarntae/backend:latest -f Backend/Dockerfile Backend'
            }
        }

        stage('Build Frontend + Nginx') {
            steps {
                sh 'docker build -t jarntae/nginx:latest -f nginx/Dockerfile .'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker compose -f docker-compose.yml up -d --build'
            }
        }
    }
}
