pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = 'dockerhub-cred' // ใส่ ID ของ Docker Hub credentials
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'testdeploy',
                    credentialsId: 'github-cred', // ใส่ ID GitHub Personal Access Token
                    url: 'https://github.com/Capstone-Project-Warehouse-68/Capstone-Warehouse.git'
            }
        }

        stage('Build Backend') {
            steps {
                sh 'docker build -t jarntae/backend:latest -f Backend/Dockerfile Backend'
            }
        }

        stage('Build Frontend + Nginx') {
            steps {
                sh 'docker build -t jarntae/nginx:latest -f nginx/Dockerfile .'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${DOCKERHUB_CREDENTIALS}", usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh 'docker push jarntae/backend:latest'
                    sh 'docker push jarntae/nginx:latest'
                }
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker-compose -f docker-compose.yml up -d --build'
            }
        }
    }
}
